<#
#
# Module manifest for module 'Just-In-time'
#
# Generated by: Andreas Lucas (aka Kili)
#
# Generated on: 8/16/2024
# updated: 18/12/2024 by Andreas Luy
#

Disclaimer:
This sample script is not supported under any Microsoft standard support program or service. 
The sample script is provided AS IS without warranty of any kind. Microsoft further disclaims 
all implied warranties including, without limitation, any implied warranties of merchantability 
or of fitness for a particular purpose. The entire risk arising out of the use or performance of 
the sample scripts and documentation remains with you. In no event shall Microsoft, its authors, 
or anyone else involved in the creation, production, or delivery of the scripts be liable for any 
damages whatsoever (including, without limitation, damages for loss of business profits, business 
interruption, loss of business information, or other pecuniary loss) arising out of the use of or 
inability to use the sample scripts or documentation, even if Microsoft has been advised of the 
possibility of such damages

This module file contains the user functions to request the administrator privileges

Version 0.1.20241014
    New commands added to manage the server search base

Implemented commands:
    Add-JitDelegation
        Add a new ACL to a OU
    Add-JitserverOU
        Add a new OU / container as search base for Tier 1 computers
    Get-JITconfig
        Displays the current configuration
    Get-JitDelegation
        Display the current assinged ACL
    Get-JitServerOU
        Displays the current Tier 1 member server search base
    Get-UserElevationStatus
        Show the elevation of a user
    New-AdminRequest
        requesting a new elevation for a user
    Remove-JITDelegation
        deletes a ACL from a OU
    Remove-JITserverOU
        Deletes a Tier 1 Meber server searchbase
#>

@{

# Script module or binary module file associated with this manifest.
#RootModule = '0.1\just-in-time-request.psm1'


# Version number of this module.
ModuleVersion = '0.1.20241014'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '852ae4b3-a649-44db-86de-e2798f7d24bc'

# Author of this module
Author = 'Andreas Lucas (aka Kili)'

# Company or vendor of this module
#CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2024 Andreas Lucas (aka Kili). All rights reserved.'

# Description of the functionality provided by this module
Description = 'Just-In-time Administration module. '

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
 RequiredModules = @("ActiveDirectory")

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('0.1\just-in-time-request.psm1','0.1\just-in-time-delegationconfig.psm1','0.1\just-in-time-configuration.psm1','0.1\just-in-time-GUIs.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    "New-AdminRequest"
    "Get-AdminStatus"
    "Get-UserElevationStatus"
    "Get-JITconfig"
    "Get-JitDelegation"
    "Get-JitserverOU"
    "Remove-JitDelegation"
    "Remove-JitServerOU"
    "Add-JitDelegation"
    "Add-JITServerOU"
    "New-BreakMsgBox"
    "New-WarningMsgBox"
    "Register-JITScheduleTask"
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(

)

# Variables to export from this module
#VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

