<#
Script Info

Author: Andreas Lucas [MSFT]
Download:

.SYNOPSIS
    Creates an example Group Policy that grants each T1JIT server group local administrator rights.
.DESCRIPTION
    Loads the active JIT configuration through Get-JITConfig and creates a complete computer GPO
    in every configured domain. Each GPO contains a Group Policy Preference for the built-in local
    Administrators group (well-known SID S-1-5-32-544). The preference adds the server-specific AD
    group generated by T1JIT without deleting existing local group members.

    In multi-domain mode, the generated member name is:
    <GroupDomainNetBIOS>\<AdminPrefix>%AD-DNSDomainName%<DomainSeparator>%ComputerName%

    In single-domain mode, the generated member name is:
    <GroupDomainNetBIOS>\<AdminPrefix>%ComputerName%

    GroupDomainNetBIOS is resolved from AdminGroupOU in the JIT configuration. This ensures
    that every GPO references the domain in which the central T1JIT groups are created, while
    AD-DNSDomainName still identifies the domain of the managed server in multi-domain mode.

    For each domain, the script creates the GPO AD object and SYSVOL structure, writes Groups.xml,
    registers the Local Users and Groups client-side extension, increments the GPO computer
    version, and links the policy to matching T1Searchbase OUs.
.PARAMETER ConfigurationFile
    Optional JIT configuration file path or Active Directory configuration common name. When
    omitted, Get-JITConfig uses JustInTimeConfig or its default AD configuration.
.PARAMETER Domain
    Optional DNS name of one configured domain for which the GPO is created. When omitted in
    multi-domain mode, the script processes every domain in the configured forest.
.PARAMETER GpoNamePrefix
    Prefix used for each domain-specific GPO name. The domain DNS name is appended.
.PARAMETER AdminPrefix
    Optional override for AdminPreFix from the JIT configuration.
.PARAMETER DomainSeparator
    Optional override for DomainSeparator from the JIT configuration.
.PARAMETER LinkDomainRoot
    Allows linking a GPO at a domain root when T1Searchbase contains <DomainRoot>. Without this
    explicit switch, the domain GPO is created but remains unlinked to avoid affecting every
    computer in that domain.
.PARAMETER Force
    Allows replacement of an existing Local Users and Groups preference in a GPO with the same
    name and suppresses the confirmation prompt. WhatIf still prevents all changes when both
    switches are supplied.
.PARAMETER Verbose
    Displays configuration loading, domain discovery, GPO creation, SYSVOL updates, and link details.
.PARAMETER WhatIf
    Shows which domain GPOs and links would be created or updated without changing Active Directory
    or SYSVOL.
.EXAMPLE
    .\New-T1JitLocalAdministratorsGpo.ps1 -WhatIf -Verbose
    Loads the active JIT configuration and displays a detailed preview of every domain-specific
    GPO and OU link without changing Active Directory or SYSVOL.
.EXAMPLE
    .\New-T1JitLocalAdministratorsGpo.ps1
    Creates one complete GPO per configured domain using AdminPreFix and DomainSeparator from
    the active JIT configuration.
.EXAMPLE
    .\New-T1JitLocalAdministratorsGpo.ps1 -Domain "child.contoso.com"
    Creates or updates the GPO only in the specified configured domain. Use this after a
    permission warning when different administrative credentials are required for that domain.
.EXAMPLE
    .\New-T1JitLocalAdministratorsGpo.ps1 `
        -ConfigurationFile "\\contoso.com\SYSVOL\contoso.com\Just-In-Time\JIT.config" `
        -AdminPrefix "T1Admin_" `
        -DomainSeparator "-" `
        -LinkDomainRoot
    Uses an explicit configuration, overrides two naming values, and permits domain-root links.
.INPUTS
    None. This script does not accept pipeline input.
.OUTPUTS
    PSCustomObject describing the GPO, target OUs, member-name expression, and Groups.xml path.
.NOTES
    Requires the GroupPolicy and ActiveDirectory Windows PowerShell modules and permissions to
    create GPOs, modify the GPO AD object, write to SYSVOL, and link GPOs to the target OUs.
    Script version 0.1.20260929.6
#>
#Requires -Version 5.1
#Requires -Modules GroupPolicy, ActiveDirectory

[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = "High")]
param(
    [Parameter()]
    [ValidateNotNullOrEmpty()]
    [string]$ConfigurationFile,

    [Parameter()]
    [ValidateNotNullOrEmpty()]
    [string]$Domain,

    [Parameter()]
    [ValidateNotNullOrEmpty()]
    [string]$GpoNamePrefix = "T1JIT - Local Administrators",

    [Parameter()]
    [ValidatePattern('^[^\\/:*?"<>|]+$')]
    [string]$AdminPrefix,

    [Parameter()]
    [ValidateLength(1, 1)]
    [string]$DomainSeparator,

    [Parameter()]
    [switch]$LinkDomainRoot,

    [Parameter()]
    [switch]$Force
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = "Stop"
$scriptVersion = "0.1.20260929.6"
Write-Host "New-T1JitLocalAdministratorsGpo.ps1 version $scriptVersion"
if ($Force) {
    $ConfirmPreference = "None"
}

<#
.SYNOPSIS
    Creates the Local Users and Groups preference XML.
.DESCRIPTION
    Builds the Group Policy Preferences schema consumed by the Local Users and Groups
    client-side extension. The preference updates the language-independent built-in
    Administrators group by SID and adds one domain-qualified T1JIT group without deleting
    existing local users or groups.
.PARAMETER MemberName
    Dynamic T1JIT AD group name to add to the local Administrators group.
.PARAMETER Changed
    Timestamp stored on the preference item.
.PARAMETER PreferenceUid
    Stable identifier of the preference item.
.EXAMPLE
    New-T1JitGroupsXml `
        -MemberName "CONTOSO\Admin_%AD-DNSDomainName%#%ComputerName%" `
        -Changed (Get-Date) `
        -PreferenceUid ([guid]::NewGuid())

    Creates an in-memory Groups.xml document for a multi-domain T1JIT configuration.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    System.Xml.XmlDocument containing a Groups preference.
.NOTES
    S-1-5-32-544 identifies the built-in Administrators group on every supported Windows
    display language. Action U and member action ADD preserve unrelated local members.
#>
function New-T1JitGroupsXml {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$MemberName,

        [Parameter(Mandatory = $true)]
        [datetime]$Changed,

        [Parameter(Mandatory = $true)]
        [guid]$PreferenceUid
    )

    # These CLSIDs are defined by the Group Policy Preferences Local Users and Groups schema.
    $document = New-Object System.Xml.XmlDocument
    $groups = $document.CreateElement("Groups")
    $groups.SetAttribute("clsid", "{3125E937-EB16-4b4c-9934-544FC6D24D26}")
    [void]$document.AppendChild($groups)

    $group = $document.CreateElement("Group")
    $group.SetAttribute("clsid", "{6D4A79E4-529C-4481-ABD0-F5BD7EA93BA7}")
    $group.SetAttribute("name", "Administrators (built-in)")
    $group.SetAttribute("image", "2")
    $group.SetAttribute("changed", $Changed.ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss"))
    $group.SetAttribute("uid", $PreferenceUid.ToString("B").ToUpperInvariant())
    $group.SetAttribute("userContext", "0")
    $group.SetAttribute("removePolicy", "0")
    [void]$groups.AppendChild($group)

    $properties = $document.CreateElement("Properties")
    $properties.SetAttribute("action", "U")
    $properties.SetAttribute("newName", "")
    $properties.SetAttribute("description", "Adds the server-specific T1JIT AD group.")
    $properties.SetAttribute("deleteAllUsers", "0")
    $properties.SetAttribute("deleteAllGroups", "0")
    $properties.SetAttribute("removeAccounts", "0")
    $properties.SetAttribute("groupSid", "S-1-5-32-544")
    $properties.SetAttribute("groupName", "Administrators (built-in)")
    [void]$group.AppendChild($properties)

    $members = $document.CreateElement("Members")
    [void]$properties.AppendChild($members)

    $member = $document.CreateElement("Member")
    $member.SetAttribute("name", $MemberName)
    $member.SetAttribute("action", "ADD")
    $member.SetAttribute("sid", "")
    [void]$members.AppendChild($member)

    return $document
}

<#
.SYNOPSIS
    Writes an XML document using UTF-8 without a byte-order mark.
.DESCRIPTION
    Serializes an XML document with deterministic indentation, Windows line endings, and
    UTF-8 encoding without a byte-order mark so Group Policy Preferences can consume the
    generated Groups.xml consistently.
.PARAMETER Document
    XML document to write.
.PARAMETER Path
    Destination file path.
.EXAMPLE
    Write-XmlDocument -Document $groupsXml -Path $groupsPath

    Writes a generated preference document to its SYSVOL destination.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    None.
.NOTES
    The caller must create the destination directory before invoking this function.
#>
function Write-XmlDocument {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [System.Xml.XmlDocument]$Document,

        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $settings = New-Object System.Xml.XmlWriterSettings
    $settings.Encoding = New-Object System.Text.UTF8Encoding($false)
    $settings.Indent = $true
    $settings.NewLineChars = "`r`n"
    $settings.NewLineHandling = [System.Xml.NewLineHandling]::Replace

    $writer = [System.Xml.XmlWriter]::Create($Path, $settings)
    try {
        $Document.Save($writer)
    }
    finally {
        $writer.Dispose()
    }
}

<#
.SYNOPSIS
    Increments the computer portion of a Group Policy version number.
.DESCRIPTION
    Decodes the combined 32-bit GPO version, preserves the upper 16-bit user version, and
    increments the lower 16-bit computer version with the same rollover behavior used by
    Group Policy.
.PARAMETER Version
    Current combined Group Policy version number.
.EXAMPLE
    Get-T1JitNextComputerVersion -Version ((7 -shl 16) -bor 12)

    Returns user version 7, computer version 13, and the recombined value.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    PSCustomObject containing the user, computer, and combined version values.
.NOTES
    Group Policy stores the user version in the upper word and the computer version in the
    lower word of versionNumber and GPT.ini.
#>
function Get-T1JitNextComputerVersion {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [int]$Version
    )

    # AD and GPT.ini must receive the same recombined version value.
    $userVersion = ($Version -shr 16) -band 0xFFFF
    $computerVersion = (($Version -band 0xFFFF) + 1) -band 0xFFFF

    return [PSCustomObject]@{
        User = $userVersion
        Computer = $computerVersion
        Combined = ($userVersion -shl 16) -bor $computerVersion
    }
}

<#
.SYNOPSIS
    Loads the active T1JIT configuration.
.DESCRIPTION
    Ensures Get-JITConfig is available, preferring repository or package-local module
    manifests before the system module path. It then loads either the explicitly supplied
    source or the standard T1JIT configuration source resolution.
.PARAMETER Source
    Optional file path or Active Directory configuration common name.
.EXAMPLE
    Get-T1JitPolicyConfiguration

    Loads the active configuration selected by Get-JITConfig.
.EXAMPLE
    Get-T1JitPolicyConfiguration -Source "\\contoso.com\SYSVOL\contoso.com\Just-In-Time\JIT.config"

    Loads an explicit JSON configuration file.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    The configuration object returned by Get-JITConfig.
.NOTES
    Get-JITConfig retains responsibility for validating configuration content and selecting
    its default environment-variable or Active Directory source.
#>
function Get-T1JitPolicyConfiguration {
    [CmdletBinding()]
    param(
        [string]$Source
    )

    if ($null -eq (Get-Command Get-JITConfig -ErrorAction SilentlyContinue)) {
        Write-Verbose "Get-JITConfig is not loaded. Searching for the T1JIT module manifest."
        $moduleCandidates = @(
            (Join-Path $PSScriptRoot "..\modules\Just-In-time.psd1"),
            (Join-Path $PSScriptRoot "..\release\modules\Just-In-time.psd1"),
            (Join-Path $PSScriptRoot "..\src\PowerShell\modules\Just-In-time.psd1")
        )
        $moduleManifest = $moduleCandidates |
            Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
            Select-Object -First 1

        if ($moduleManifest) {
            Write-Verbose "Importing the T1JIT module from '$moduleManifest'."
            Import-Module $moduleManifest -Force -ErrorAction Stop
        }
        else {
            Write-Verbose "Importing the T1JIT module through the PowerShell module path."
            Import-Module Just-In-Time -Force -ErrorAction Stop
        }
    }

    if ([string]::IsNullOrWhiteSpace($Source)) {
        Write-Verbose "Loading the active JIT configuration from the default configuration source."
        return Get-JITConfig
    }

    Write-Verbose "Loading the JIT configuration from '$Source'."
    return Get-JITConfig -ConfigurationFile $Source
}

<#
.SYNOPSIS
    Returns all domains managed by the JIT configuration.
.DESCRIPTION
    Enumerates every forest domain when multi-domain support is enabled. In single-domain
    mode it returns the first configured domain, or the local computer domain when no domain
    was configured.
.PARAMETER Configuration
    Loaded JIT configuration object.
.EXAMPLE
    Get-T1JitConfiguredDomains -Configuration $configuration

    Returns the DNS names for which domain-specific GPOs must be provisioned.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    System.String domain DNS names.
.NOTES
    Results from forest discovery are sorted and deduplicated for deterministic processing.
#>
function Get-T1JitConfiguredDomains {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $Configuration
    )

    if ($Configuration.EnableMultiDomainSupport) {
        $configuredDomains = @($Configuration.Domain)
        $forestIdentity = if ($configuredDomains.Count -gt 0) {
            [string]$configuredDomains[0]
        }
        else {
            (Get-ADDomain -Current LocalComputer -ErrorAction Stop).Forest
        }
        Write-Verbose "Discovering all domains in forest '$forestIdentity'."
        $forest = Get-ADForest -Identity $forestIdentity -ErrorAction Stop
        return @($forest.Domains | Sort-Object -Unique)
    }

    $configuredDomains = @($Configuration.Domain)
    if ($configuredDomains.Count -gt 0 -and
        -not [string]::IsNullOrWhiteSpace([string]$configuredDomains[0])) {
        Write-Verbose "Using configured single domain '$($configuredDomains[0])'."
        return @([string]$configuredDomains[0])
    }

    Write-Verbose "No domain is configured. Using the local computer domain."
    return @((Get-ADDomain -Current LocalComputer -ErrorAction Stop).DNSRoot)
}

<#
.SYNOPSIS
    Selects all configured domains or one explicitly requested domain.
.DESCRIPTION
    Returns every configured domain when no filter is supplied. When a DNS domain is
    requested, the function performs a case-insensitive lookup and returns the canonical
    configured value. An unconfigured domain is rejected before any GPO changes are attempted.
.PARAMETER ConfiguredDomains
    DNS names discovered from the active JIT configuration and forest.
.PARAMETER RequestedDomain
    Optional DNS domain selected through the Domain script parameter.
.EXAMPLE
    Select-T1JitTargetDomains `
        -ConfiguredDomains "contoso.com", "child.contoso.com" `
        -RequestedDomain "child.contoso.com"

    Returns only child.contoso.com.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    System.String DNS domain names to process.
.NOTES
    Case-insensitive matching prevents duplicate domain processing caused by casing differences.
#>
function Select-T1JitTargetDomains {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$ConfiguredDomains,

        [string]$RequestedDomain
    )

    if ([string]::IsNullOrWhiteSpace($RequestedDomain)) {
        return @($ConfiguredDomains)
    }

    $selectedDomain = $ConfiguredDomains |
        Where-Object { $_ -ieq $RequestedDomain } |
        Select-Object -First 1
    if ([string]::IsNullOrWhiteSpace([string]$selectedDomain)) {
        throw "Domain '$RequestedDomain' is not part of the configured JIT domains: $($ConfiguredDomains -join ', ')."
    }

    return @([string]$selectedDomain)
}

<#
.SYNOPSIS
    Determines whether an exception represents an authorization failure.
.DESCRIPTION
    Walks an exception and its inner exceptions looking for UnauthorizedAccessException,
    the Windows access-denied HRESULT, or established English and German Active Directory
    access-denied messages. Other failures remain fatal.
.PARAMETER Exception
    Exception raised while provisioning one domain GPO.
.EXAMPLE
    Test-T1JitPermissionError -Exception $_.Exception

    Returns true when a per-domain provisioning failure was caused by missing permissions.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    System.Boolean.
.NOTES
    The message checks cover common GroupPolicy and ActiveDirectory module error wrappers
    that do not retain UnauthorizedAccessException as their outer exception type.
#>
function Test-T1JitPermissionError {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [System.Exception]$Exception
    )

    $currentException = $Exception
    while ($null -ne $currentException) {
        if ($currentException -is [System.UnauthorizedAccessException] -or
            $currentException.HResult -eq -2147024891 -or
            $currentException.Message -match '(?i)access is denied|access denied|insufficient access rights|unauthorized|zugriff (?:wurde )?verweigert|unzureichende zugriffsrechte') {
            return $true
        }
        $currentException = $currentException.InnerException
    }

    return $false
}

<#
.SYNOPSIS
    Resolves the domain in which T1JIT administrator groups are created.
.DESCRIPTION
    Extracts the DNS domain from the DC components of AdminGroupOU and resolves its Active
    Directory domain object. The NetBIOS name from that object is used to qualify the GPP
    member reference because all T1JIT groups are stored in this central OU.
.PARAMETER Configuration
    Loaded JIT configuration containing AdminGroupOU.
.EXAMPLE
    Get-T1JitGroupDomain -Configuration $configuration

    Resolves the account domain containing the configured JIT administrator-group OU.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    The Active Directory domain object for the configured administrator-group OU.
.NOTES
    The function fails explicitly when AdminGroupOU contains no domain components or the
    resolved domain has no NetBIOS name.
#>
function Get-T1JitGroupDomain {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $Configuration
    )

    $adminGroupOu = [string]$Configuration.AdminGroupOU
    if ([string]::IsNullOrWhiteSpace($adminGroupOu)) {
        throw "AdminGroupOU is empty in the JIT configuration."
    }

    $groupDomainDnsName = @($adminGroupOu -split ',' |
        Where-Object { $_ -match '^\s*DC=' } |
        ForEach-Object { $_ -replace '(?i)^\s*DC=', '' }) -join '.'
    if ([string]::IsNullOrWhiteSpace($groupDomainDnsName)) {
        throw "Could not determine the JIT group domain from AdminGroupOU '$adminGroupOu'."
    }

    Write-Verbose "Resolving the central JIT group domain '$groupDomainDnsName' from AdminGroupOU '$adminGroupOu'."
    $groupDomain = Get-ADDomain -Identity $groupDomainDnsName -Server $groupDomainDnsName -ErrorAction Stop
    if ([string]::IsNullOrWhiteSpace([string]$groupDomain.NetBIOSName)) {
        throw "The NetBIOS name of the JIT group domain '$groupDomainDnsName' is empty."
    }

    return $groupDomain
}

<#
.SYNOPSIS
    Creates the domain-qualified T1JIT group expression used by Group Policy Preferences.
.DESCRIPTION
    Reproduces the T1JIT group-naming convention and prefixes it with the NetBIOS name of
    the central group-account domain. In multi-domain mode the server DNS domain remains a
    dynamic part of the group name through the AD-DNSDomainName environment variable.
.PARAMETER Configuration
    Loaded JIT configuration controlling single-domain or multi-domain group naming.
.PARAMETER AdminPrefix
    Effective T1JIT administrator-group prefix.
.PARAMETER DomainSeparator
    Effective separator between server domain and computer name.
.PARAMETER GroupDomainNetBIOSName
    NetBIOS name of the domain containing the central T1JIT groups.
.EXAMPLE
    Get-T1JitGroupMemberName `
        -Configuration $configuration `
        -AdminPrefix "Admin_" `
        -DomainSeparator "#" `
        -GroupDomainNetBIOSName "CONTOSO"

    Returns the domain-qualified dynamic member expression for the active naming mode.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    System.String containing a domain-qualified dynamic group-name expression.
.NOTES
    The returned expression is stored literally in Groups.xml and expanded by Group Policy
    Preferences on each target computer.
#>
function Get-T1JitGroupMemberName {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $Configuration,

        [Parameter(Mandatory = $true)]
        [string]$AdminPrefix,

        [Parameter(Mandatory = $true)]
        [string]$DomainSeparator,

        [Parameter(Mandatory = $true)]
        [string]$GroupDomainNetBIOSName
    )

    $groupName = if ($Configuration.EnableMultiDomainSupport) {
        "$AdminPrefix%AD-DNSDomainName%$DomainSeparator%ComputerName%"
    }
    else {
        "$AdminPrefix%ComputerName%"
    }

    return "$GroupDomainNetBIOSName\$groupName"
}

<#
.SYNOPSIS
    Resolves configured T1Searchbase entries that belong to one domain.
.DESCRIPTION
    Expands relative search bases against the current domain, retains fully qualified
    distinguished names only for their owning domain, optionally includes DomainRoot, and
    validates every OU through Active Directory before it is used as a GPO link target.
.PARAMETER Configuration
    Loaded JIT configuration object.
.PARAMETER DomainInfo
    Active Directory domain object.
.PARAMETER IncludeDomainRoot
    Includes the domain distinguished name when <DomainRoot> is configured.
.EXAMPLE
    Get-T1JitDomainLinkTargets -Configuration $configuration -DomainInfo $domain

    Returns validated OU distinguished names for one domain while excluding DomainRoot.
.EXAMPLE
    Get-T1JitDomainLinkTargets `
        -Configuration $configuration `
        -DomainInfo $domain `
        -IncludeDomainRoot

    Also permits the domain distinguished name as a link target.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    Distinguished names suitable as GPO link targets.
.NOTES
    DomainRoot is excluded by default because a domain-root link can affect every computer
    in that domain.
#>
function Get-T1JitDomainLinkTargets {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $Configuration,

        [Parameter(Mandatory = $true)]
        $DomainInfo,

        [switch]$IncludeDomainRoot
    )

    $targets = foreach ($searchBase in @($Configuration.T1Searchbase)) {
        $configuredSearchBase = [string]$searchBase
        if ([string]::IsNullOrWhiteSpace($configuredSearchBase)) {
            continue
        }

        if ($configuredSearchBase -eq "<DomainRoot>") {
            if ($IncludeDomainRoot) {
                Write-Verbose "Using domain root '$($DomainInfo.DistinguishedName)' as a link target."
                $DomainInfo.DistinguishedName
            }
            else {
                Write-Verbose "Skipping domain-root link for '$($DomainInfo.DNSRoot)' because -LinkDomainRoot was not supplied."
            }
            continue
        }

        $targetDn = if ($configuredSearchBase -match '(?i)(?:^|,)DC=') {
            $configuredSearchBase
        }
        else {
            "$configuredSearchBase,$($DomainInfo.DistinguishedName)"
        }

        $targetDomain = @($targetDn -split ',' |
            Where-Object { $_ -match '^\s*DC=' } |
            ForEach-Object { $_ -replace '(?i)^\s*DC=', '' }) -join '.'
        if ($targetDomain -ieq $DomainInfo.DNSRoot) {
            Write-Verbose "Validating GPO link target '$targetDn' in '$($DomainInfo.DNSRoot)'."
            (Get-ADOrganizationalUnit -Identity $targetDn -Server $DomainInfo.DNSRoot -ErrorAction Stop).DistinguishedName
        }
        else {
            Write-Verbose "Skipping '$configuredSearchBase' for '$($DomainInfo.DNSRoot)' because it belongs to '$targetDomain'."
        }
    }

    return @($targets | Sort-Object -Unique)
}

<#
.SYNOPSIS
    Creates or updates one complete domain-specific T1JIT GPO.
.DESCRIPTION
    Creates or reuses the domain GPO, writes its Local Users and Groups preference into
    SYSVOL, registers the required client-side extension on the GPO object, increments the
    computer version in Active Directory and GPT.ini, and creates any missing OU links.
.PARAMETER DomainInfo
    Active Directory domain object in which the GPO is created.
.PARAMETER GpoName
    Domain-specific GPO display name.
.PARAMETER MemberName
    Dynamic T1JIT AD group expression added to local Administrators.
.PARAMETER LinkTargets
    Domain or OU distinguished names to which the GPO is linked.
.PARAMETER ReplaceExisting
    Allows replacement of an existing Groups.xml preference.
.EXAMPLE
    Install-T1JitDomainGpo `
        -DomainInfo $domain `
        -GpoName "T1JIT - Local Administrators - contoso.com" `
        -MemberName "CONTOSO\Admin_%ComputerName%" `
        -LinkTargets "OU=Servers,DC=contoso,DC=com"

    Creates a complete GPO and links it to the Servers OU.
.INPUTS
    None. Pipeline input is not supported.
.OUTPUTS
    PSCustomObject describing the complete domain GPO.
.NOTES
    Direct SYSVOL and GPO-object updates require permissions beyond creating a GPO.
    ReplaceExisting must only be enabled after the caller has obtained confirmation or Force.
#>
function Install-T1JitDomainGpo {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $DomainInfo,

        [Parameter(Mandatory = $true)]
        [string]$GpoName,

        [Parameter(Mandatory = $true)]
        [string]$MemberName,

        [string[]]$LinkTargets,

        [switch]$ReplaceExisting
    )

    $existingGpo = Get-GPO -Name $GpoName -Domain $DomainInfo.DNSRoot -ErrorAction SilentlyContinue
    if ($null -ne $existingGpo -and -not $ReplaceExisting) {
        throw "GPO '$GpoName' already exists in '$($DomainInfo.DNSRoot)'. Use -Force only after reviewing its existing Local Users and Groups preferences."
    }

    $gpo = if ($null -eq $existingGpo) {
        Write-Verbose "Creating GPO '$GpoName' in '$($DomainInfo.DNSRoot)'."
        New-GPO -Name $GpoName -Domain $DomainInfo.DNSRoot -Comment "Adds the server-specific T1JIT AD group to the built-in local Administrators group." -ErrorAction Stop
    }
    else {
        Write-Verbose "Updating existing GPO '$GpoName' in '$($DomainInfo.DNSRoot)'."
        $existingGpo
    }

    # A complete GPO consists of both its AD object and matching GUID-named SYSVOL folder.
    $gpoGuid = $gpo.Id.ToString("B").ToUpperInvariant()
    $gpoAdPath = "CN=$gpoGuid,CN=Policies,CN=System,$($DomainInfo.DistinguishedName)"
    $gpoAdObject = Get-ADObject -Identity $gpoAdPath -Server $DomainInfo.DNSRoot -Properties gPCMachineExtensionNames, versionNumber -ErrorAction Stop
    $policyPath = "\\$($DomainInfo.DNSRoot)\SYSVOL\$($DomainInfo.DNSRoot)\Policies\$gpoGuid"
    $groupsDirectory = Join-Path $policyPath "Machine\Preferences\Groups"
    $groupsPath = Join-Path $groupsDirectory "Groups.xml"

    Write-Verbose "Writing Local Users and Groups preference to '$groupsPath'."
    New-Item -Path $groupsDirectory -ItemType Directory -Force | Out-Null
    $groupsXml = New-T1JitGroupsXml -MemberName $MemberName -Changed (Get-Date) -PreferenceUid ([guid]::NewGuid())
    Write-XmlDocument -Document $groupsXml -Path $groupsPath

    $version = Get-T1JitNextComputerVersion -Version ([int]$gpoAdObject.versionNumber)
    $newVersion = $version.Combined

    # Register the Local Users and Groups CSE and its tool extension on the computer side.
    $localUsersAndGroupsCse = "[{17D89FEC-5C44-4972-B12D-241CAEF74509}{79F92669-4224-476C-9C5C-6EFB4D87DF4A}]"
    $machineExtensions = [string]$gpoAdObject.gPCMachineExtensionNames
    if ($machineExtensions -notlike "*{17D89FEC-5C44-4972-B12D-241CAEF74509}*") {
        Write-Verbose "Registering the Local Users and Groups client-side extension."
        $machineExtensions += $localUsersAndGroupsCse
    }

    Write-Verbose "Updating GPO computer version to '$($version.Computer)' (combined value '$newVersion')."
    Set-ADObject -Identity $gpoAdPath -Server $DomainInfo.DNSRoot -Replace @{
        gPCMachineExtensionNames = $machineExtensions
        versionNumber = $newVersion
    } -ErrorAction Stop

    # GPT.ini and the AD versionNumber must remain identical for client change detection.
    $gptIniPath = Join-Path $policyPath "GPT.ini"
    @(
        "[General]"
        "Version=$newVersion"
    ) | Set-Content -LiteralPath $gptIniPath -Encoding ASCII

    foreach ($linkTarget in @($LinkTargets)) {
        $inheritance = Get-GPInheritance -Target $linkTarget -Domain $DomainInfo.DNSRoot -ErrorAction Stop
        $linkExists = @($inheritance.GpoLinks | Where-Object { $_.DisplayName -eq $GpoName }).Count -gt 0
        if (-not $linkExists) {
            Write-Verbose "Linking GPO '$GpoName' to '$linkTarget'."
            New-GPLink -Name $GpoName -Target $linkTarget -Domain $DomainInfo.DNSRoot -LinkEnabled Yes -ErrorAction Stop | Out-Null
        }
        else {
            Write-Verbose "GPO '$GpoName' is already linked to '$linkTarget'."
        }
    }

    return [PSCustomObject]@{
        PSTypeName = "T1JIT.GroupPolicyConfiguration"
        GpoName = $GpoName
        GpoId = $gpo.Id
        Domain = $DomainInfo.DNSRoot
        LinkTarget = @($LinkTargets)
        MemberName = $MemberName
        LocalGroupSid = "S-1-5-32-544"
        GroupsXmlPath = $groupsPath
        ComputerVersion = $version.Computer
        Applied = $true
    }
}

Import-Module GroupPolicy -ErrorAction Stop
Import-Module ActiveDirectory -ErrorAction Stop

$configuration = Get-T1JitPolicyConfiguration -Source $ConfigurationFile
$effectiveAdminPrefix = if ($PSBoundParameters.ContainsKey("AdminPrefix")) {
    $AdminPrefix
}
else {
    [string]$configuration.AdminPreFix
}
$effectiveDomainSeparator = if ($PSBoundParameters.ContainsKey("DomainSeparator")) {
    $DomainSeparator
}
else {
    [string]$configuration.DomainSeparator
}

if ([string]::IsNullOrWhiteSpace($effectiveAdminPrefix)) {
    throw "AdminPreFix is empty in the JIT configuration. Supply -AdminPrefix or correct JIT.config."
}
if ($effectiveDomainSeparator.Length -ne 1) {
    throw "DomainSeparator must contain exactly one character. Supply -DomainSeparator or correct JIT.config."
}

$groupDomain = Get-T1JitGroupDomain -Configuration $configuration
$memberName = Get-T1JitGroupMemberName `
    -Configuration $configuration `
    -AdminPrefix $effectiveAdminPrefix `
    -DomainSeparator $effectiveDomainSeparator `
    -GroupDomainNetBIOSName $groupDomain.NetBIOSName

$configuredDomains = @(Get-T1JitConfiguredDomains -Configuration $configuration)
$domains = @(Select-T1JitTargetDomains `
    -ConfiguredDomains $configuredDomains `
    -RequestedDomain $Domain)
Write-Verbose "JIT groups are stored in '$($groupDomain.DNSRoot)' and referenced through NetBIOS name '$($groupDomain.NetBIOSName)'."
Write-Verbose "Resolved member expression '$memberName'."
Write-Verbose "Processing $($domains.Count) domain(s): $($domains -join ', ')."
foreach ($domainDnsName in $domains) {
    try {
        Write-Verbose "Resolving domain and link targets for '$domainDnsName'."
        $domainInfo = Get-ADDomain -Identity $domainDnsName -Server $domainDnsName -ErrorAction Stop
        $linkTargets = @(Get-T1JitDomainLinkTargets `
            -Configuration $configuration `
            -DomainInfo $domainInfo `
            -IncludeDomainRoot:$LinkDomainRoot)
        $gpoName = "$GpoNamePrefix - $($domainInfo.DNSRoot)"
        $existingGpo = Get-GPO -Name $gpoName -Domain $domainInfo.DNSRoot -ErrorAction SilentlyContinue
        $replaceExisting = $null -ne $existingGpo
        $targetDescription = if ($linkTargets.Count -gt 0) {
            "$($domainInfo.DNSRoot): $($linkTargets -join ', ')"
        }
        else {
            "$($domainInfo.DNSRoot): create unlinked GPO"
        }

        if (-not $LinkDomainRoot -and @($configuration.T1Searchbase) -contains "<DomainRoot>") {
            Write-Warning "T1Searchbase contains <DomainRoot> for '$($domainInfo.DNSRoot)'. GPO '$gpoName' will not be linked at the domain root unless -LinkDomainRoot is explicitly supplied."
        }

        $operation = if ($replaceExisting) {
            if (-not $Force) {
                Write-Warning "GPO '$gpoName' already exists in '$($domainInfo.DNSRoot)'. Confirm the following prompt to overwrite its Local Users and Groups preference."
            }
            "Overwrite existing GPO '$gpoName' with member '$memberName'"
        }
        else {
            "Create new GPO '$gpoName' with member '$memberName'"
        }

        if ($PSCmdlet.ShouldProcess($targetDescription, $operation)) {
            Install-T1JitDomainGpo `
                -DomainInfo $domainInfo `
                -GpoName $gpoName `
                -MemberName $memberName `
                -LinkTargets $linkTargets `
                -ReplaceExisting:$replaceExisting
        }
        else {
            [PSCustomObject]@{
                PSTypeName = "T1JIT.GroupPolicyConfiguration"
                GpoName = $gpoName
                Domain = $domainInfo.DNSRoot
                LinkTarget = @($linkTargets)
                MemberName = $memberName
                LocalGroupSid = "S-1-5-32-544"
                Applied = $false
            }
        }
    }
    catch {
        if (-not (Test-T1JitPermissionError -Exception $_.Exception)) {
            throw
        }

        $retryCommand = "& '$PSCommandPath' -Domain '$domainDnsName'"
        if (-not [string]::IsNullOrWhiteSpace($ConfigurationFile)) {
            $escapedConfigurationFile = $ConfigurationFile.Replace("'", "''")
            $retryCommand += " -ConfigurationFile '$escapedConfigurationFile'"
        }
        Write-Warning "Insufficient permissions to create or update the T1JIT Group Policy in domain '$domainDnsName': $($_.Exception.Message)"
        Write-Warning "Run the script again with credentials authorized in that domain: $retryCommand"

        [PSCustomObject]@{
            PSTypeName = "T1JIT.GroupPolicyConfiguration"
            GpoName = "$GpoNamePrefix - $domainDnsName"
            Domain = $domainDnsName
            LinkTarget = @()
            MemberName = $memberName
            LocalGroupSid = "S-1-5-32-544"
            Applied = $false
            Error = "PermissionDenied"
        }
    }
}
